name: Run Python Runner

on:
 push:
  branches: [main]

jobs:
 run-python:
  runs-on: self-hosted
  steps:
   - name: Checkout repo
     uses: actions/checkout@v3

   - name: Run python script
     run: python main.py
